import type { Metadata } from 'next';
import './globals.css';
import Link from 'next/link';
import { Control } from './Control';
export const metadata: Metadata = {
  title: 'web tutorial',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const res = await fetch(process.env.NEXT_PUBLIC_API_URL + 'posts', {
    next: { revalidate: 0 },
  });
  const temps = await res.json();
  return (
    <html>
      <body>
        <h1>
          <Link href="/">web</Link>
        </h1>
        <ol>
          {temps.map((temp: any) => {
            return (
              <li key={temp.id}>
                <Link href={`/read/${temp.id}`}>{temp.title}</Link>
              </li>
            );
          })}
        </ol>
        {children}
        <br></br>
        <br></br>
        <Control />
      </body>
    </html>
  );
}
